### ISSUE TITLE
Sample Transcripts + Transcript Format

### ISSUE THREAD

**Issue by larue3000** [senthilchandrasegaran/textplorer#1]
Greetings Senthil,

Recently discovered your paper, Integrating Visual Analytics Support for Grounded Theory Practice in Qualitative Text Analysis and installed the textplorer.

It would be greatly appreciated if you could share details of the transcript data file format.  A sample transcript would be extremely helpful as well.

Best Regards,
Troy

**Comment by larue3000** [comment]
I'm going to make the presumption that it uses the VizScribe format 

A corresponding transcript file with timestamps. The format of the transcript should be:
   start time,end time,speaker,dialog
   00:00:01.5,00:00:03.0,Travis Bickle,You talkin' to me?

**Comment by senthilchandrasegaran** [comment]
Apologies for the years-late response. Yes, you're right, it does follow the VizScribe format. Sorry again!
